### ISSUE TITLE
这个怎么用啊 是要编译吗 没学过python？

### ISSUE THREAD

**Issue by zero617** [LanceLiang2018/Wenku8ToEpub#3]

**Comment by zero617** [comment]
另外可以修复一下那个下载的网站吗？

**Comment by chiro2001** [comment]
Python 的话不需要编译，但是还是需要安装依赖库的。
先[安装](https://zhuanlan.zhihu.com/p/104502997) Python3，然后到这个工程的目录执行：

```shell
python3 -m pip install -r requirements.txt
```

再然后就可以 `python3 wenku8toepub.py -h` 查看使用帮助了。

~~刚从那另一边 wenku8toepub 看到你这个 issue，你就给我发 issue 了， 好家伙~~

**Comment by chiro2001** [comment]
> 
> 
> 另外可以修复一下那个下载的网站吗？

wenku8.herokuapp.com 吗... 这个上古巨坑实在没有时间填了...

之前也想过用新坑填旧坑，但是工作量也很大。

见→https://github.com/chiro2001/chibrary

**Comment by zero617** [comment]
![image](https://user-images.githubusercontent.com/67105838/135181079-6eac3bb5-477d-422a-8fc5-d8d246d6e1e3.png)
这是为什么啊？

**Comment by chiro2001** [comment]
> ![image](https://user-images.githubusercontent.com/67105838/135181079-6eac3bb5-477d-422a-8fc5-d8d246d6e1e3.png) 这是为什么啊？

应该是安装依赖的时候网络不好，可以用国内源：https://www.jianshu.com/p/dfbb90995a2c 。

**Comment by zero617** [comment]
![image](https://user-images.githubusercontent.com/67105838/135184400-da69c743-dcac-4c09-baf8-d2056c329931.png)
用了阿里云的镜像源 还是不行

**Comment by chiro2001** [comment]
试试清华源吧，再不行的话让我看看所有的错误输出，拉到最底部。

**Comment by zero617** [comment]
![image](https://user-images.githubusercontent.com/67105838/135185345-7f3d6274-148d-438f-b22c-c13a88f07643.png)

**Comment by chiro2001** [comment]
居然是我从来没遇到过的问题...😨
查了一下有可能是电脑的代理有问题，检查一下电脑设置里的代理设置（设置→网络→代理），关闭代理。
如果使用过翻墙软件的话关掉。

**Comment by zero617** [comment]
ok了 多谢
